---
title: "IMAGINE Microbiome Profile"
author: "Surette Laboratory"
date: "5/12/2023"
output: html_document
---

```{r, echo=FALSE, message=FALSE}

library(tidyverse)
library(phyloseq)
library(AfterSl1p)


```

## Importing background data

```{r, echo=FALSE, message=FALSE}

#Importing the dada2 files
seqtab.nochim <- read.csv("data/seqtab_nochim_transposed_IMG-HC_v34.csv")
row.names(seqtab.nochim) <- seqtab.nochim$X
seqtab.nochim %>% select(-X) -> seqtab.nochim

# Importing taxonomic assignment
taxa <- read.csv("data/taxa_IMG-HC_v34_silva138.csv")
row.names(taxa) <- taxa$X

#import the data into phyloseq:
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=T), 
               tax_table(as.matrix(taxa)))

# adding mapfile later in here:
data.frame(Study_ID= sample_names(ps),
           Status= paste("Healthy")) -> ps_mapfile

# just manually add one random imagine number as study participants for
# generating a report

sample = "IMG106"

ps_mapfile %>%
  mutate(Status= case_when(Study_ID == sample ~ paste(Study_ID),
                           TRUE ~ paste(Status))) -> ps_mapfile

row.names(ps_mapfile) <- ps_mapfile$Study_ID
sample_data(ps) <- ps_mapfile

ps
```

## Clean the data
```{r}
summary(taxa_sums(ps))
summary(sample_sums(ps))

# Remove host sequences
ps = prop_tax_down(ps, indic = FALSE)
ps
ps = subset_taxa(ps, Kingdom %in% c('Bacteria','Archaea') &
                       !(Phylum %in% Kingdom) & 
                     (Family != 'Mitochondria'))
ps

# Take relative abundance before any abundance filtering
ps_rel = transform_sample_counts(ps, function(x) x/sum(x))
ps_rel

# Remove low-abundance taxa
keep = filter_taxa(ps, function(x) mean(x) > 10)
ps_rel_filt = prune_taxa(keep, ps_rel)
ps_filt = prune_taxa(keep, ps)
```

## Microbial Composition

Here, you can see relative abundance of your gut bacteria
```{r, echo=FALSE, message=FALSE}

ps_i <- subset_samples(ps_filt, Status  == "IMG106")

ps_i_rel = subset_samples(ps_rel_filt, Status == 'IMG106')

ps_gen_df <- make_phy_df(ps_i_rel, rank = "Genus", cutoff = 0.001, 
            count = FALSE)

#Only show the participant of interest:
# ps_gen_df %>% 
#   filter(Study_ID == sample) -> ps_gen_df
# you already did this filtering with the Status filter.

barplt = plot_tax_bar(ps_gen_df, rank = "Family", sample = "Study_ID", 
             leglen = 10, legloc = "right") 

barplt


```


## Microbiome diversity

This figure shows the diversity of microbiome in healthy individual. Each dot
shows one IMAGINE participant and your microbiome profile is shown in green.

```{r, echo=FALSE, message=FALSE}

bray_dis_ps = phyloseq::distance(ps_rel_filt, method = 'bray')
bray_ord_ps = ordinate(ps_rel_filt, method = 'PCoA', distance = bray_dis_ps)


ord_plt = plot_ordination(ps_rel_filt, bray_ord_ps, color="Status") +
    scale_color_manual(values = c("Healthy" = "#bdbdbd",
                                  "IMG106" = "#1a9850")) +
    geom_point(alpha = 0.5, size=3) +
    ggplot2::theme_classic() +
    theme(legend.title = element_blank(),
          legend.text  = element_text(size=15),
        text = element_text(size = 10),
        legend.position = "right")

ord_plt
```


```{r, echo=FALSE, message=FALSE}


#description <- read.csv("data/description.txt", sep = "\t")


```


